### ISSUE TITLE
Bug en el website MultimediaProject

### ISSUE THREAD

**Issue by jvillamarino** [jesusvillamarin/platzi-course-git-github#2]
# Que sucede?
   No funciona los estilos bootstrap en IE8 y Microsoft Edge

# Es de alto valor el requerimiento?
  - [x] No
 
- [x] Si
  # Como puedo llegar a ese bug?
    Habrá el navegador IE8 ó Microsoft Edge y entre a la pagina -->https://jesavillamarino.github.io/MultimediaProject/

**Comment by jesavillamarino** [comment]
perfecto

**Comment by jvillamarino** [comment]
perfecto
